### ISSUE TITLE
Place default locale outside any folder?

### ISSUE THREAD

**Issue by alvarotrigo** [36web/gulp-static-i18n-html#1]
When using on the shell the following command, I get a `es` folder and the default one outside any folder, as it should be [according to the docs](https://github.com/claudetech/node-static-i18n#example):

```shell
static-i18n -l en -i en -i es --fileFormat yml --allowHtml --i18n "{\"keyseparator\": \"::\"}" www
```

When using the followin gulp command I get them both inside a folder:

```javascript

gulp.task('international', function() {
  return gulp.src('www/*.html')
    .pipe(staticI18nHtml({
        locale: 'en',
        locales: ['en', 'es'],
        fileFormat: 'yml',
        allowHtml: true,
        i18n: {
            keyseparator: '::'
        }
    }))
    .pipe(gulp.dest('./i18n'));
});
```

What am I doing wrong?

**Comment by 36web** [comment]
@alvarotrigo thanks for reporting.
It will be fixed in the next version.

**Comment by alvarotrigo** [comment]
Thanks for that!! ;)
