### ISSUE TITLE
allowHTML doesn't work

### ISSUE THREAD

**Issue by alvarotrigo** [36web/gulp-static-i18n-html#2]
The option `allowHtml` doesn't seem to work either.

**Comment by 36web** [comment]
Could you please provide some more details.
What kind of HTML tags you use in your locale files?
Or some sample code to reproduce the problem.

**Comment by alvarotrigo** [comment]
Sure. Here's an isolated reproduction:

```html
<p data-t data-t-interpolate>
    {{text here}}
    <div>Whatever here</div>
</p>
```

Resulting in:
```html
<p>
    texto aqui
    Whatever here
</p>
```

When using:

```javascript
gulp.task('international', function() {
  return gulp.src('www/*.html')
    .pipe(staticI18nHtml({
        locale: 'en',
        locales: ['en', 'es'],
        fileFormat: 'yml',
        allowHtml: true,
        i18n: {
            keyseparator: '::'
        }
    }))
    .pipe(gulp.dest('./i18n'));
});
```

**Comment by alvarotrigo** [comment]
MMmm sorry for this! I've just realised this might be directly related with [a bug in the node module](https://github.com/claudetech/node-static-i18n/pull/17) for which I suggested a quick fix.

Not quite sure if the changes in the module were pushed to npm.
