### ISSUE TITLE
Support for 'fixPaths' option

### ISSUE THREAD

**Issue by pcoeper** [36web/gulp-static-i18n-html#4]
Hey,

I was wondering if there is a way to support the 'fixPaths' option? I did take a look into the relevant code of 'node-static-i18n' and apparently this is only possible when calling 'processFile()' or 'processDir()' which will set the 'options.file' property correctly. Do you think there is a way to enable this option in this tool?

Thanks for your help!

**Comment by pcoeper** [comment]
I found a way to make the path modification work but it only works if you have a single *.html file to be processed. In my case the html.index template file is placed in `app/assets/www/index.html`. My config looks like this

```
function translate() {
    return gulp.src('./app/assets/www/index.html')
        .pipe(staticI18nHtml({
            locale: 'de',
            locales: ['de', 'en'],
            files: './app/assets/www/index.html',
            file: './app.index.html'
        }))
        .pipe(gulp.dest('./app'));
}
```

which results in a german translation file `app/index.html` and an english version in `app/en/index.html` with all relatives path to stylesheets and scripts modified.

Still this is not the most elegant way. I would assume passing a `lookupDir` variable together with the `options` object to the `staticI18nHtml()` method which then calls `processDir()` instead of `process()`. If I'll find the time I can provide a PR.

Hope this helps others.

**Comment by 36web** [comment]
@pcoeper thanks for the feedback.
Seems the package needs some updates. I'll check if it's possible to support it.
PR is always welcomed, and maybe we could discuss a proper way to support the option.

**Comment by pcoeper** [comment]
@36web thanks for the response! I would love to contribute since I guess I’ll have some time within the next weeks when not much more is possible due to the corona virus... Might be a dumb question but since I haven’t really contributed in open source packages before I was wondering what is the best way to do so? Forking your repo or simply cloning and branching? Thanks in advance.

**Comment by 36web** [comment]
@pcoeper the way to contribute would be - fork and send PR.
